Fixed hide-corners bug
ewlsh/dynamic-panel-transparency pull request #140
Opened 2021-04-12 18:52 UTC by ajbucci

Hey, this is my first pull request so apologies if I haven't done this quite right! This should fix the issue "Panel corners black after toggling overview"

Fixes #139

2021-04-12 21:14 UTC, ajbucci commented
This is only a partial fix. The black corners will return if the background custom opacities are adjusted, though re-enabling the extension fixes it until the opacities are adjusted again. It may be due to how set_corner_color is working in theming.js?

2021-04-26 20:48 UTC, Bananaman commented
@ewlsh @ajbucci Thanks for trying to solve this issue. It looks like the solution here might be over-engineered?

I posted a comment on the issue ticket, which mentions how to solve this problem with 1 line of CSS:

https://github.com/ewlsh/dynamic-panel-transparency/issues/139#issuecomment-827136784

2021-04-30 04:43 UTC, ewlsh requested changes

2021-04-30 04:43 UTC, ewlsh commented on dynamic-panel-transparency@rockon999.github.io/stylesheet.css
> +.panel-corner {
```suggestion
.dpt-panel-hide-corners {
```

2021-04-30 04:43 UTC, ewlsh commented on dynamic-panel-transparency@rockon999.github.io/theming.js
> +/**
Remove `register_hide_corners` - you don't need a dynamic stylesheet for a static style.

2021-04-30 04:43 UTC, ewlsh commented on dynamic-panel-transparency@rockon999.github.io/extension.js
> +                    if (stylesheet.indexOf('background') !== -1 && stylesheet.indexOf('panel-') !== -1 && stylesheet.indexOf('panel-hide-corners') == -1) {
Revert.

2021-04-30 04:43 UTC, ewlsh commented on dynamic-panel-transparency@rockon999.github.io/extension.js
> +                    if (stylesheet.indexOf('background') !== -1 && stylesheet.indexOf('panel-') !== -1 && stylesheet.indexOf('panel-hide-corners') == -1) {
Revert.

2021-04-30 04:43 UTC, ewlsh commented on dynamic-panel-transparency@rockon999.github.io/extension.js
> +                    if (stylesheet.indexOf('background') !== -1 && stylesheet.indexOf('panel.dpt.css') !== -1 && stylesheet.indexOf('panel-hide-corners') == -1) {
Revert.

2021-04-30 04:43 UTC, ewlsh commented on dynamic-panel-transparency@rockon999.github.io/extension.js
> +    let hide_corners = Theming.register_hide_corners();
```suggestion
```

2021-04-30 04:43 UTC, ewlsh commented on dynamic-panel-transparency@rockon999.github.io/extension.js
> +    /* Register hide corners. */
```suggestion
```

2021-04-30 04:43 UTC, ewlsh commented on dynamic-panel-transparency@rockon999.github.io/extension.js
> +        if (hide_corners !== null) {
Remove conditional.

2021-04-30 04:43 UTC, ewlsh commented on dynamic-panel-transparency@rockon999.github.io/stylesheet.css
> +  -panel-corner-border-width: 0px;}
```suggestion
  -panel-corner-border-width: 0px;
}

```

2021-04-30 04:43 UTC, ewlsh commented on dynamic-panel-transparency@rockon999.github.io/extension.js
> +
```suggestion

```

2021-04-30 04:45 UTC, ewlsh commented
@ajbucci I reviewed this and listed the necessary changes, I'll apply them myself and commit this weekend unless you'd like to.

2021-05-01 03:36 UTC, ajbucci commented
@ewlsh Thanks for taking the time to review the changes! I'm a bit shot at the moment as my wife and I just had our first child this past week and are still adjusting. Go ahead and apply your changes/suggestions this weekend. Thanks again!

2021-11-11 17:27 UTC, ewlsh commented
Changes were manually applied, thank you :wave:

2021-11-11 17:27 UTC, closed without merging